# Generated by Django 5.2 on 2025-04-08 05:17

import ckeditor_uploader.fields
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Строго вида site.ru', max_length=100, unique=True, verbose_name='Домен')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Title главной страницы')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Meta-description главной страницы')),
                ('keywords', models.CharField(default='', max_length=500, verbose_name='Meta-keywords главной страницы')),
                ('h1', models.CharField(default='', max_length=250, verbose_name='Заголовок главной страницы')),
                ('main_text', ckeditor_uploader.fields.RichTextUploadingField(help_text='Не менее 300 символов', validators=[django.core.validators.MinLengthValidator(300)], verbose_name='Текст на главной')),
                ('logo', models.ImageField(help_text='Форматы: png, jpg, jpeg', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Логотип сайта')),
                ('favicon', models.ImageField(help_text='фавикон в формате .ico', null=True, upload_to='static/pbn/favicons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ico',))], verbose_name='favicon')),
                ('blog_title', models.CharField(default='', max_length=250, verbose_name='Title страницы блога')),
                ('blog_description', models.CharField(default='', max_length=500, verbose_name='Description страницы блога')),
                ('blog_keywords', models.CharField(default='', max_length=250, verbose_name='Meta-keywords страницы блога')),
                ('blog_name', models.CharField(default='', max_length=250, verbose_name='H1 страницы блога')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Title')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Meta-description')),
                ('h1', models.CharField(default='', max_length=250, verbose_name='Заголовок H1')),
                ('keywords', models.CharField(default='', max_length=250, verbose_name='Meta-keywords')),
                ('category_slug', models.SlugField(help_text='При создании поставьте любой символ. Поле заполнится автоматически.', max_length=100, verbose_name='URL')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['-domain', '-name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Meta-description')),
                ('keywords', models.CharField(default='', max_length=500, verbose_name='Meta-keywords')),
                ('slug', models.SlugField(help_text='При создании поставьте любой символ. Поле заполнится автоматически.', max_length=100, verbose_name='URL')),
                ('img_preview', models.ImageField(null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-превью')),
                ('text_preview', models.TextField(default='', help_text='Не более 300 символов вместе с пробелами', max_length=300, verbose_name='Текст-превью')),
                ('created', models.DateField(default=datetime.datetime(2025, 4, 8, 8, 17, 42, 227376), verbose_name='Дата создания')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(help_text='Не менее 300 символов', validators=[django.core.validators.MinLengthValidator(300)], verbose_name='Содержание статьи')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='pbn.category', verbose_name='Категория')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='MembransLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_user', models.SlugField(help_text='Символный код ссылки-прокладки. Только латиница в нижним регистре и тире. Например: my-new-link', max_length=100, verbose_name='URL-прокладки')),
                ('link_money_site', models.CharField(help_text='URL финальной страницы на Money Site', max_length=150, verbose_name='URL Money Site')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Ссылки-прокладки',
            },
        ),
        migrations.CreateModel(
            name='OtherPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(help_text='При создании поставьте любой символ. Поле заполнится автоматически.', max_length=100, verbose_name='URL')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Title')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Meta-description')),
                ('keywords', models.CharField(default='', max_length=250, verbose_name='Meta-keywords')),
                ('h1', models.CharField(default='', max_length=250, verbose_name='Заголовок H1')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Содержание')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Другие страницы',
            },
        ),
    ]
