# Generated by Django 5.2 on 2025-04-08 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 8, 8, 19, 50, 677113), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='domain',
            field=models.CharField(help_text='формат site.ru', max_length=100, unique=True, verbose_name='Домен'),
        ),
    ]
