# Generated by Django 5.2 on 2025-04-09 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0002_alter_article_created_alter_domains_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 9, 9, 21, 25, 485282), verbose_name='Дата создания'),
        ),
        migrations.DeleteModel(
            name='MembransLinks',
        ),
    ]
