# Generated by Django 5.2 on 2025-04-09 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0003_alter_article_created_delete_membranslinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 9, 9, 26, 2, 545405), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='LinksMembrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_user', models.CharField(default='', help_text='Символный код ссылки-прокладки. Только латиница в нижним регистре и тире. Например: my-new-link', max_length=100, verbose_name='URL-прокладки')),
                ('link_money_site', models.CharField(default='', help_text='URL финальной страницы на Money Site', max_length=100, verbose_name='URL Money Site')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Ссылки-прокладки',
            },
        ),
        migrations.CreateModel(
            name='LinksRedirects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_link', models.CharField(default='', help_text='Начинается строго со знака /. Например /page.html или /page', max_length=100, verbose_name='Откуда редирект')),
                ('finish_link', models.CharField(default='', help_text='Начинается строго со знака /. Например /page.html. Если редирект на главную, просто пишем - /.', max_length=100, verbose_name='Куда редирект')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Ссылки-редиректы',
            },
        ),
    ]
