# Generated by Django 5.2 on 2025-04-13 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0004_alter_article_created_linksmembrans_linksredirects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='domains',
            name='google_analytics',
            field=models.CharField(default='', help_text='Например: G-8C1FN89PWR', max_length=100, null=True, verbose_name='Счетчик Google Analytics'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 13, 10, 43, 18, 384305), verbose_name='Дата создания'),
        ),
    ]
