# Generated by Django 5.2 on 2025-04-13 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0005_alter_category_options_domains_google_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='yandex_metrika',
            field=models.CharField(default='', help_text='Например: 94153371', max_length=100, null=True, verbose_name='Счетчик Yandex metrika'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 13, 10, 55, 12, 432268), verbose_name='Дата создания'),
        ),
    ]
