# Generated by Django 5.2 on 2025-04-15 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0006_domains_yandex_metrika_alter_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='yandex_webmaster',
            field=models.CharField(default='', help_text='Например: ffbe325dc3c6cf09', max_length=150, null=True, verbose_name='Номер Яндекс.Вебмастера'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 10, 28, 44, 775491), verbose_name='Дата создания'),
        ),
    ]
