# Generated by Django 5.2 on 2025-04-15 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0007_domains_yandex_webmaster_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 10, 38, 30, 94997), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='google_analytics',
            field=models.CharField(blank=True, default='', help_text='Например: G-8C1FN89PWR', max_length=100, verbose_name='Счетчик Google Analytics'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='yandex_metrika',
            field=models.CharField(blank=True, default='', help_text='Например: 94153371', max_length=100, verbose_name='Счетчик Yandex metrika'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='yandex_webmaster',
            field=models.CharField(blank=True, default='', help_text='Например: ffbe325dc3c6cf09', max_length=150, verbose_name='Номер Яндекс.Вебмастера'),
        ),
    ]
