# Generated by Django 5.2 on 2025-04-30 06:13

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0009_article_page_view_article_time_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 9, 13, 3, 282893), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_view',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Не более 300 символов вместе с пробелами', max_length=300, verbose_name='Текст-превью'),
        ),
    ]
