# Generated by Django 5.2 on 2025-07-10 06:51

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0010_alter_article_created_alter_article_page_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='template',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')], default=1, verbose_name='Выбор шаблона'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 9, 51, 41, 949332), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Не более 300 символов вместе с пробелами. Только текст и ссылки.', max_length=300, verbose_name='Текст-превью'),
        ),
    ]
