# Generated by Django 5.2 on 2025-07-10 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0011_domains_template_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 10, 6, 47, 468340), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='template',
            field=models.IntegerField(choices=[('first', 'first'), ('second', 'second')], default=1, verbose_name='Выбор шаблона'),
        ),
    ]
