# Generated by Django 5.2 on 2025-07-10 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0012_alter_article_created_alter_domains_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 10, 10, 6, 723074), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='template',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second')], default='first', max_length=150, verbose_name='Выбор шаблона'),
        ),
    ]
