# Generated by Django 5.2 on 2025-07-10 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0013_alter_article_created_alter_domains_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='template',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 10, 11, 57, 997272), verbose_name='Дата создания'),
        ),
    ]
