# Generated by Django 5.2 on 2025-07-15 07:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0015_domains_template_alter_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_preview',
            field=models.ImageField(blank=True, default='', upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 15, 10, 19, 8, 114943), verbose_name='Дата создания'),
        ),
    ]
