# Generated by Django 5.2 on 2025-07-15 08:07

import ckeditor_uploader.fields
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0016_category_img_preview_alter_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='table_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Содержание статьи в виде списка с якорями', verbose_name='Список заголовков'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 15, 11, 7, 37, 764987), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_preview',
            field=models.ImageField(blank=True, default='', help_text='Для некоторых шаблонов', upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-превью'),
        ),
    ]
