# Generated by Django 5.2 on 2025-07-16 04:03

import ckeditor_uploader.fields
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0017_article_table_content_alter_article_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя автора')),
                ('spec', models.CharField(help_text='Не более 300 символов', max_length=300, verbose_name='Специализация автора')),
                ('preview', models.CharField(help_text='Не более 600 символов', max_length=600, verbose_name='Описание автора')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Meta-description')),
                ('keywords', models.CharField(default='', max_length=500, verbose_name='Meta-keywords')),
                ('slug', models.SlugField(help_text='При создании поставьте любой символ. Поле заполнится автоматически.', max_length=100, verbose_name='URL')),
                ('img_preview', models.ImageField(null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Фото автора')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 16, 7, 3, 15, 496202), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='table_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Маркированный список подзаголовков с якорями (необязательно)', verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Не менее 300 символов', validators=[django.core.validators.MinLengthValidator(300)], verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='pbn.author', verbose_name='Автор'),
        ),
    ]
