# Generated by Django 5.2 on 2025-07-16 04:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0018_author_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автора', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='author',
            name='domain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 16, 7, 12, 27, 295494), verbose_name='Дата создания'),
        ),
    ]
