# Generated by Django 5.2 on 2025-07-16 04:18

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0019_alter_author_options_author_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 16, 7, 18, 45, 253252), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='author',
            name='preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Информация об авторе'),
        ),
    ]
