# Generated by Django 5.2 on 2025-07-17 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0020_alter_article_created_alter_author_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='authors_description',
            field=models.CharField(default='', help_text='Заполнять, если такая страница есть в шаблоне', max_length=300, null=True, verbose_name='Description страницы авторов'),
        ),
        migrations.AddField(
            model_name='domains',
            name='authors_keywords',
            field=models.CharField(default='', help_text='Заполнять, если такая страница есть в шаблоне', max_length=300, null=True, verbose_name='Keywords страницы авторов'),
        ),
        migrations.AddField(
            model_name='domains',
            name='authors_title',
            field=models.CharField(default='', help_text='Заполнять, если такая страница есть в шаблоне', max_length=300, null=True, verbose_name='Title страницы авторов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 17, 7, 32, 35, 239285), verbose_name='Дата создания'),
        ),
    ]
