# Generated by Django 5.2 on 2025-07-17 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0021_domains_authors_description_domains_authors_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 17, 7, 35, 57, 821326), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='authors_description',
            field=models.CharField(blank=True, default='', help_text='Заполнять, если такая страница есть в шаблоне', max_length=300, verbose_name='Description страницы авторов'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='authors_keywords',
            field=models.CharField(blank=True, default='', help_text='Заполнять, если такая страница есть в шаблоне', max_length=300, verbose_name='Keywords страницы авторов'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='authors_title',
            field=models.CharField(blank=True, default='', help_text='Заполнять, если такая страница есть в шаблоне', max_length=300, verbose_name='Title страницы авторов'),
        ),
    ]
