# Generated by Django 5.2 on 2025-07-18 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0023_alter_article_author_alter_article_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',), 'verbose_name': 'Автора', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='author',
            name='last_mod',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 8, 17, 59, 723832), verbose_name='Дата создания'),
        ),
    ]
