# Generated by Django 5.2 on 2025-08-12 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0024_alter_author_options_author_last_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 12, 9, 35, 47, 808662), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='template',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('blog_third', 'blog_third')], default='first', max_length=150, verbose_name='Выбор шаблона'),
        ),
    ]
