# Generated by Django 5.2 on 2025-08-13 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0025_alter_article_created_alter_domains_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='info_footer',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: «Блог-3»', max_length=300, verbose_name='Текст о сайте в футере'),
        ),
        migrations.AddField(
            model_name='domains',
            name='name_site',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: «Блог-3»', max_length=100, verbose_name='Название сайта в шапке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 13, 9, 53, 49, 918603), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='template',
            field=models.CharField(choices=[('first', 'Блог-1'), ('second', 'Блог-2'), ('blog_third', 'Блог-3')], default='first', max_length=150, verbose_name='Выбор шаблона'),
        ),
    ]
