# Generated by Django 5.2 on 2025-08-15 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0026_domains_info_footer_domains_name_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='emal_start',
            field=models.CharField(default='info', help_text='Например: info или help (домен подтянется сам)', max_length=50, verbose_name='Имя ящика'),
        ),
        migrations.AddField(
            model_name='domains',
            name='year_start',
            field=models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2015', max_length=50, verbose_name='Год запуска проекта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 15, 9, 12, 10, 759108), verbose_name='Дата создания'),
        ),
    ]
