# Generated by Django 5.2 on 2025-08-15 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0027_domains_emal_start_domains_year_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='phone',
            field=models.CharField(default='', help_text='В удобочитаемом виде: +7-(495)-233-23-23', max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 15, 9, 47, 35, 469428), verbose_name='Дата создания'),
        ),
    ]
