# Generated by Django 5.2 on 2025-08-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0028_domains_phone_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 15, 10, 25, 5, 629702), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='emal_start',
            field=models.CharField(default='info', help_text='Для всех шаблонов. Например: info или help (домен подтянется сам)', max_length=50, verbose_name='Имя ящика'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='info_footer',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: «Блог-2», «Блог-3»', max_length=300, verbose_name='Текст о сайте в футере'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='phone',
            field=models.CharField(default='', help_text='Для шаблонов:«Блог-3» и всех коммерческих. В удобочитаемом виде: +7-(495)-233-23-23', max_length=50, verbose_name='Телефон'),
        ),
    ]
