# Generated by Django 5.2 on 2025-08-15 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0029_alter_article_created_alter_domains_emal_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 15, 10, 31, 2, 989904), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Для шаблонов:«Блог-3» и всех коммерческих. В удобочитаемом виде: +7-(495)-233-23-23', max_length=50, verbose_name='Телефон'),
        ),
    ]
