# Generated by Django 5.2 on 2025-08-19 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0030_alter_article_created_alter_domains_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='google_webmaster',
            field=models.CharField(blank=True, default='', help_text='Например: WQIWvovWZPf97NwMWKDEBnYOKZevVnd3YC0H6Sl5vNs', max_length=150, verbose_name='Номер Google Search Console'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 19, 11, 15, 15, 688148), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='year_start',
            field=models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2015', max_length=50, verbose_name='Год запуска проекта'),
        ),
    ]
