# Generated by Django 5.2 on 2025-08-20 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0031_domains_google_webmaster_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='region',
            field=models.CharField(blank=True, default='', help_text='Используется для микроразметки. Например: Москва', max_length=50, verbose_name='Город расположения'),
        ),
        migrations.AddField(
            model_name='domains',
            name='street',
            field=models.CharField(blank=True, default='', help_text='Используется для микроразметки. Например: Полежавевская дом 1', max_length=50, verbose_name='Адрес (без города)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 8, 20, 9, 29, 35, 940239), verbose_name='Дата создания'),
        ),
    ]
