# Generated by Django 5.2 on 2025-09-17 05:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0033_domains_extra_picture_domains_extra_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructortextservice',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блок'},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.RenameField(
            model_name='domains',
            old_name='telegtam',
            new_name='telegram',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 9, 17, 8, 51, 42, 86692), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='extra_picture',
            field=models.ImageField(blank=True, help_text='Используется для шаблонов: услуги-1 (пропорции 3x2)', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Дополнительное изображение на главной'),
        ),
    ]
