# Generated by Django 5.2 on 2025-09-17 06:44

import ckeditor_uploader.fields
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0034_alter_constructortextservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 9, 17, 9, 44, 4, 655469), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='constructortextservice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-блока'),
        ),
        migrations.AlterField(
            model_name='constructortextservice',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст'),
        ),
    ]
