# Generated by Django 5.2 on 2025-09-18 05:41

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0035_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='service_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Используется для всех коммерческих шаблонов', verbose_name='Текст страницы - все услуги'),
        ),
        migrations.AddField(
            model_name='domains',
            name='service_title',
            field=models.CharField(blank=True, default='', help_text='Используется для коммерческих шаблонов', max_length=200, verbose_name='Заголовок для страницы: все услуги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 9, 18, 8, 41, 9, 106882), verbose_name='Дата создания'),
        ),
    ]
