# Generated by Django 5.2 on 2025-09-18 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0036_domains_service_text_domains_service_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='service_description',
            field=models.CharField(blank=True, default='', help_text='Используется для коммерческих шаблонов', max_length=300, verbose_name='Desription для страницы: все услуги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 9, 18, 8, 44, 31, 136852), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='service_title',
            field=models.CharField(blank=True, default='', help_text='Используется для коммерческих шаблонов', max_length=200, verbose_name='Title для страницы: все услуги'),
        ),
    ]
