# Generated by Django 5.2 on 2025-09-19 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0037_domains_service_description_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер (коммерческий шаблон 1)'},
        ),
        migrations.AddField(
            model_name='service',
            name='name_table_price',
            field=models.CharField(blank=True, default='', help_text='Например: Наименование', max_length=300, verbose_name='Название столбца с услугами'),
        ),
        migrations.AddField(
            model_name='service',
            name='value_table_price',
            field=models.CharField(blank=True, default='', help_text='Например: Стоимость руб за м2', max_length=300, verbose_name='Наименование столбца с ценами на услуги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 9, 27, 46, 987711), verbose_name='Дата создания'),
        ),
    ]
