# Generated by Django 5.2 on 2025-09-20 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0038_alter_mainslider_options_service_name_table_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='description_all_authors',
            field=models.CharField(blank=True, default='', help_text='Используется во всех шаблонах', max_length=100, verbose_name='Description на странице всех авторов'),
        ),
        migrations.AddField(
            model_name='domains',
            name='name_info',
            field=models.CharField(blank=True, default='', help_text='Используется для коммерческих шаблонов (новости, статьи, публикации и т.д.)', max_length=100, verbose_name='Название инфо-раздела в коммерческих шаблонах'),
        ),
        migrations.AddField(
            model_name='domains',
            name='title_all_authors',
            field=models.CharField(blank=True, default='', help_text='Используется во всех шаблонах', max_length=100, verbose_name='Title на странице всех авторов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 9, 20, 8, 35, 8, 330810), verbose_name='Дата создания'),
        ),
    ]
