# Generated by Django 5.2 on 2025-09-20 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0039_domains_description_all_authors_domains_name_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='description_all_authors',
        ),
        migrations.RemoveField(
            model_name='domains',
            name='title_all_authors',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 9, 20, 8, 37, 5, 711465), verbose_name='Дата создания'),
        ),
    ]
