# Generated by Django 5.2 on 2025-10-14 06:09

import ckeditor_uploader.fields
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0040_remove_domains_description_all_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='action_name',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: коммерческий-2', max_length=300, verbose_name='Заголовок акции для услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='action_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Шаблоны: коммерческий-2', verbose_name='Текст-акции'),
        ),
        migrations.AddField(
            model_name='service',
            name='action_value',
            field=models.IntegerField(default=10, help_text='Шаблоны: коммерческий-2', verbose_name='Величина скидки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 9, 9, 54, 811813), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='template',
            field=models.CharField(choices=[('first', 'Блог-1'), ('second', 'Блог-2'), ('blog_third', 'Блог-3'), ('blog_fourth', 'Блог-4'), ('service_1', 'Услуги-1'), ('service_2', 'Услуги-2')], default='first', max_length=150, verbose_name='Выбор шаблона'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='preview_picture',
            field=models.ImageField(help_text='размер 1350x900', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-слайда'),
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Например: Выгода до 20% на ручную мойку', max_length=100, verbose_name='Заголовок Акции')),
                ('picture', models.ImageField(help_text='размер 1312x736', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акцию (шаблоны: коммерческий-2)',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Не отображается на сайте', max_length=100, verbose_name='Название картинки')),
                ('picture', models.ImageField(help_text='размер 1312x736', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка-')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинку (шаблоны: коммерческий-2)',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', help_text='Например: как починить автомобиль?', max_length=300, verbose_name='Вопрос')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Ответ')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопрос - ответ',
            },
        ),
    ]
