# Generated by Django 5.2 on 2025-10-19 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0041_service_action_name_service_action_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name': 'вариант акции', 'verbose_name_plural': 'Акция (шаблоны: коммерческий-2)'},
        ),
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name': 'вариант картинки', 'verbose_name_plural': 'Картинки галерии (шаблоны: коммерческий-2)'},
        ),
        migrations.AddField(
            model_name='author',
            name='expirense',
            field=models.IntegerField(default=1, verbose_name='Опыт автора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 10, 19, 8, 27, 46, 856640), verbose_name='Дата создания'),
        ),
    ]
