# Generated by Django 5.2 on 2025-11-13 07:22

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0042_alter_actions_options_alter_galery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_preview',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: коммерческий-3', max_length=100, verbose_name='Загружаем символов UTF (иконку)'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_preview',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: коммерческий-3', max_length=500, verbose_name='Превью-текст для услуги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 13, 10, 22, 14, 889791), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='author',
            name='expirense',
            field=models.IntegerField(default=1, help_text='Для шаблонов: коммерческий-2', verbose_name='Опыт автора'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='template',
            field=models.CharField(choices=[('first', 'Блог-1'), ('second', 'Блог-2'), ('blog_third', 'Блог-3'), ('blog_fourth', 'Блог-4'), ('service_1', 'Услуги-1'), ('service_2', 'Услуги-2'), ('service_3', 'Услуги-3')], default='first', max_length=150, verbose_name='Выбор шаблона'),
        ),
        migrations.AlterField(
            model_name='service',
            name='action_name',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: коммерческий-2,3', max_length=300, verbose_name='Заголовок акции для услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='action_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Шаблоны: коммерческий-2,3', verbose_name='Текст-акции'),
        ),
        migrations.AlterField(
            model_name='service',
            name='action_value',
            field=models.IntegerField(default=10, help_text='Шаблоны: коммерческий-2,3', verbose_name='Величина скидки'),
        ),
    ]
