# Generated by Django 5.2 on 2025-11-13 07:39

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0043_service_icon_preview_service_text_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 13, 10, 39, 43, 276783), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_preview',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: коммерческий-3 (например  🎉)', max_length=100, verbose_name='Символ UTF-8'),
        ),
        migrations.CreateModel(
            name='BenifitsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Например: Экспертиза', max_length=300, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='10 лет опыта в сфере строительства', verbose_name='Описание преимущества')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('icon', models.CharField(default='', help_text='Например:  🎉', max_length=100, verbose_name='Символов UTF-8')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
