# Generated by Django 5.2 on 2025-11-14 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0044_alter_article_created_alter_service_icon_preview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benifitscompany',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества (коммерческие шаблоны: 3)'},
        ),
        migrations.RenameField(
            model_name='benifitscompany',
            old_name='service',
            new_name='domain',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 8, 39, 12, 861208), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='benifitscompany',
            name='text',
            field=models.CharField(blank=True, default='', help_text='Например: 10 лет опыта в сфере строительства (не более 150 символов)', max_length=150, verbose_name='Описание преимущества'),
        ),
    ]
