# Generated by Django 5.2 on 2025-11-14 05:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0045_alter_benifitscompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 8, 53, 38, 912545), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('name', models.CharField(default='', help_text='Например: Оптимизация бизнес процессов', max_length=300, verbose_name='Название')),
                ('text', models.CharField(blank=True, default='', help_text='Например: Реализовали комплексный проект по автоматизации розничной сети из 50+ магазинов с интеграцией всех систем.', max_length=150, verbose_name='Описание кейса')),
                ('category_case', models.CharField(blank=True, default='', help_text='Например: Трансформация', max_length=150, verbose_name='Категория кейса')),
                ('image', models.ImageField(help_text='размер 440x320', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Картинка кейса')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Кейсы',
                'verbose_name_plural': 'Кейс (коммерческие шаблоны: 3)',
            },
        ),
    ]
