# Generated by Django 5.2 on 2025-11-14 06:18

import ckeditor_uploader.fields
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0046_alter_article_created_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 9, 18, 29, 175313), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('author', models.CharField(default='', help_text='Например: Иван Иванов', max_length=300, verbose_name='Автор')),
                ('post', models.CharField(blank=True, default='', help_text='Например: Операционный директор СЕО-Импульс.', max_length=150, verbose_name='Должность')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст отзыва')),
                ('image', models.ImageField(help_text='размер 56x56', null=True, upload_to='static/pbn/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Фото автора')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Кейсы',
                'verbose_name_plural': 'Кейс (коммерческие шаблоны: 3)',
            },
        ),
    ]
