# Generated by Django 5.2 on 2025-11-14 06:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0047_alter_article_created_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзыв (коммерческие шаблоны: 3)'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 9, 35, 11, 610556), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='HowWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('name', models.CharField(default='', help_text='Например: Анализ', max_length=300, verbose_name='Названи этапа')),
                ('text', models.CharField(blank=True, default='', help_text='Например: Изучаем ваш бизнес, цели и текущую ситуацию', max_length=150, verbose_name='Описание этапа')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.domains', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги (коммерческие шаблоны: 3)',
            },
        ),
    ]
