# Generated by Django 5.2 on 2025-11-14 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0048_alter_review_options_alter_article_created_howwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 9, 46, 11, 54211), verbose_name='Дата создания'),
        ),
    ]
