# Generated by Django 5.2 on 2025-11-14 07:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0049_alter_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='one_text',
            field=models.CharField(blank=True, default='', help_text='Шаблоны: коммерческий-3', max_length=800, verbose_name='Единственный текстовый блок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 10, 0, 12, 617465), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='DescriptionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=100, help_text='Чем ближе к нулю,тем выше', verbose_name='Сортировка')),
                ('name', models.CharField(default='', help_text='Например: Стратегический анализ', max_length=300, verbose_name='Тезис')),
                ('text', models.CharField(blank=True, default='', help_text='Например: Разработка и внедрение эффективных бизнес-процессов для снижения издержек', max_length=150, verbose_name='Описание тезиса')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbn.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Тезис',
                'verbose_name_plural': 'Тезисы (коммерческие шаблоны: 3)',
            },
        ),
    ]
