# Generated by Django 5.2 on 2025-11-14 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0050_service_one_text_alter_article_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionservice',
            old_name='domain',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 10, 6, 4, 228745), verbose_name='Дата создания'),
        ),
    ]
