# Generated by Django 5.2 on 2025-11-14 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn', '0051_rename_domain_descriptionservice_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionservice',
            name='icon',
            field=models.CharField(default='', help_text='Например:  🎉', max_length=100, verbose_name='Символов UTF-8'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 10, 7, 50, 364692), verbose_name='Дата создания'),
        ),
    ]
